-- Create traits_questions table
-- Stores initial personality questions
CREATE TABLE IF NOT EXISTS traits_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_text TEXT NOT NULL,
  category TEXT NOT NULL,
  options_json JSONB NOT NULL
);

-- Create decision_nodes table
-- Stores hard logic flowchart nodes
CREATE TABLE IF NOT EXISTS decision_nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('question', 'result')),
  yes_next_id BIGINT REFERENCES decision_nodes(id),
  no_next_id BIGINT REFERENCES decision_nodes(id),
  final_result_pet_name TEXT
);

-- Create user_sessions table
-- Stores training data and user journey
CREATE TABLE IF NOT EXISTS user_sessions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  trait_answers JSONB,
  path_taken JSONB,
  recommended_pet TEXT,
  user_feedback_score INTEGER
);

-- Add Row Level Security (RLS) policies (Optional but recommended)
-- For now, we enable read access for everyone for questions/nodes, and insert for sessions.
ALTER TABLE traits_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public questions are viewable by everyone" ON traits_questions
  FOR SELECT USING (true);

ALTER TABLE decision_nodes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public nodes are viewable by everyone" ON decision_nodes
  FOR SELECT USING (true);

ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert their own sessions" ON user_sessions
  FOR INSERT WITH CHECK (true);
-- Note: You might want to restrict SELECT on user_sessions to admins only or the creating user if auth is implemented.
